### ISSUE TITLE
Cut new CRAN release

### ISSUE THREAD

**Issue by holub008** [holub008/xrf#13]
- Need to update version number (and possibly add a commit hook).
- List out changes from last release

Possibly also verify R 4.0 compatibility.

**Comment by holub008** [comment]
@topepo Are you happy with current state of `xrf`? I'm going to start a CRAN release if so.

**Comment by topepo** [comment]
Yes. I had planned on some other api changes but other crises came up. It's good and I can get `rules` ready for submission with this version. 

Thanks!

**Comment by topepo** [comment]
How's the submission going?

**Comment by holub008** [comment]
@topepo Just submitted - will let you know when it's through.

**Comment by holub008** [comment]
> Dear maintainer, thanks, package xrf_0.2.0.tar.gz is on its way to CRAN.
