### ISSUE TITLE
problem with interpreting rules

### ISSUE THREAD

**Issue by Naviden** [holub008/xrf#15]
running the first example of readme and calculating the `coef`, I get a list of rules. the first ten are:

![image](https://user-images.githubusercontent.com/16959102/102795118-ab29a080-43ac-11eb-97ea-9f973296520a.png)

I can't understand how should I assign each rule to each label:  "<= 50k" and ">50k".

**Comment by holub008** [comment]
What do you mean by "assign each rule to each label".

These coefficients represent a linear model. Rules are evaluated to true/false (0/1 dummy encoded) and then the coefficient vector is dotted with the dummy vector to produce a prediction (log odds in the event of a binomial outcome).

You should use the `predict` function if you want to run this. If you just want to evaluate the rules to true/false, check out `model.matrix`.

**Comment by Naviden** [comment]
My goal is to extract an IF THEN set of rules. For example _IF "A" <10 & "B" >5 THEN "label_1"_. Can I get it using `predict`? could you provide a simple example?

**Comment by holub008** [comment]
That's simply not how RuleFit works. RuleFit produces a linear model as the end result; linear models predict from a linear combination of predictors and coefficients, not a set of mutually exclusive rule evaluations. Furthermore, if you're predicting labels, that linear combination is producing a posterior probability which is not a classification. You'd have to impose a threshold on the posteriors to actually make a label classification.

What you're describing (a set of rules directly mapping to a prediction) could be achieved with a single decision tree, which you could try fitting with e.g. `rpart`. However single decision trees may not perform as well as more complex models, depending on your data. More complex models like XGBoost, RuleFit, etc. rely on ensembling, which doesn't produce predictions in the way you describe.
