### ISSUE TITLE
Current xgboost objective is now deprecated

### ISSUE THREAD

**Issue by juliasilge** [holub008/xrf#19]
The objective function for xgboost like this:

https://github.com/holub008/xrf/blob/ea02526427e72a2d97bd6fdb3922dd7343c52dbc/R/xrf.R#L89

has been deprecated. When we use xrf we get warnings such as:

```
WARNING: amalgamation/../src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror
```

**Comment by holub008** [comment]
Shoot! Thanks @juliasilge, I'll patch this up.

**Comment by holub008** [comment]
Update: I'm trying to clear other warnings up to go with this release. Namely #16, which seems to possibly require an upstream fix. Depending on if there's something I can do to resolve or not, I will progress release.

**Comment by holub008** [comment]
@juliasilge 0.2.1 is released, and this should be patched, in addition to some other warnings/noise from XGB. I did a reverse depends check on `rules`, but let me know if anything looks off on your end. Thanks for filing!

**Comment by juliasilge** [comment]
Thank you so much @holub008! 🙌
